[project]
name = "volley-rag"
version = "0.1.0"
description = "An app utilizing rag models to answer specific questions about the official FIVB volleyball rules"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "transformers>=4.44.2",
]
